name: Docker Image CI for GHCR

on:
  push:
    tags: ["v*.*.*"]

jobs:
  push_to_registry:
    name: Push Image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/vahan90/yapg:latest
            ghcr.io/vahan90/yapg:${{ github.ref_name }}

      - name: Image digest
        run: |
          echo "Image pushed: ghcr.io/${{ github.repository_owner }}/yapg:${{ github.ref_name }}"
